spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant_db?useSSL=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Venky@081a
  jpa:
    hibernate:
      ddl-auto: update   
  application: 
    name: RESTAURANT-SEARCH-SERVICE
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 9091